<a href="https://colab.research.google.com/github/ArunadeviRamesh/Detection-of-COVID-Deep-Learning-99.3-Accuracy-/blob/master/COVID_19_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objs as go
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
df=pd.read_csv("/content/drive/My Drive/covid data/tamilnadu/TN confirmed and active 15 and 5 days.csv")
df.head(3)

district      date  ...  confirmed one week  death one week
0  Tamil Nadu  7/3/2020  ...                   1               0
1  Tamil Nadu  8/3/2020  ...                   1               0
2  Tamil Nadu  9/3/2020  ...                   1               0

[3 rows x 10 columns]

In [ ]:
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))

Accuracy r2_score 99.5559263625811
ACCURACY= 99.64582489868108
MAE= 879.9767426294285
MSE= confirmed 15days      1.586754e+07
death 15 days         3.753360e+03
confirmed one week    1.934123e+06
death one week        5.397839e+02
dtype: float64
Final rmse value is = confirmed 15days      3983.408229
death 15 days           61.264669
confirmed one week    1390.727644
death one week          23.233251
dtype: float64


In [ ]:
print(lr.predict([[175678,2551]]))
print(lr.predict([[185678,3500]]))
lr.predict([[180643,2626]])

[[283717.51614998   4320.18262297 211871.70921769   3140.82483363]]
[[249925.67090885   4696.84474731 215882.78336427   4065.11033203]]


array([[291515.62695303,   4442.99669331, 217822.66968292,
          3232.37454336]])

In [ ]:
df=pd.read_csv("/content/drive/My Drive/covid data/chennai/Chennai confirmed and death 15 and 5 days.csv")
df.head(3)

District       date  ...  confirmed one week  death one week
0  Chennai  4/21/2020  ...                 528               0
1  Chennai  4/22/2020  ...                 575               0
2  Chennai  4/23/2020  ...                 678               8

[3 rows x 10 columns]

In [ ]:
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))

Accuracy r2_score -388.45350896621727
ACCURACY= 99.28712343622638
MAE= 6510.205320156985
MSE= confirmed after 15 days    1.615706e+10
death after 15 days        3.870594e+03
confirmed one week         1.743291e+06
death one week             7.292933e+02
dtype: float64
Final rmse value is = confirmed after 15 days    127110.418465
death after 15 days            62.214095
confirmed one week           1320.337545
death one week                 27.005431
dtype: float64


In [ ]:
lr.predict([[88337,1475]])


array([[111925.1342877 ,   1949.71831237,  99413.59236294,
          1690.54315522]])

In [ ]:
df=pd.read_csv("/content/drive/My Drive/covid data/maharashtra/Maharshtra confirmed and death 15 and 5.csv")
df.head(3)

district       date  active  ...  death 15  confirmed 5  death 5
0  Maharashtra   9/3/2020     NaN  ...         2           14        0
1  Maharashtra  10/3/2020     NaN  ...         3           32        0
2  Maharashtra  11/3/2020     NaN  ...         3           32        0

[3 rows x 10 columns]

In [ ]:
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))

Accuracy r2_score 99.23834274620478
ACCURACY= 99.72394230412065
MAE= 1945.334970254419
MSE= confirmed15    3.832464e+07
death 15       1.482015e+05
confirmed 5    4.012689e+06
death 5        1.000981e+05
dtype: float64
Final rmse value is = confirmed15    6190.690142
death 15        384.969506
confirmed 5    2003.169747
death 5         316.382796
dtype: float64


In [ ]:
lr.predict([[325045,12170]])

array([[512465.3709729 ,  20859.62546654, 382336.81787414,
         14673.58392975]])

In [ ]:
df=pd.read_csv("/content/drive/My Drive/covid data/USA/USA 15 and 5.csv")
df.head(3)

district        date  active  ...  death 15  confirmed 5  death 5
0  United States  12/31/2019     NaN  ...         0            0        0
1  United States    1/1/2020     NaN  ...         0            0        0
2  United States    1/2/2020     NaN  ...         0            0        0

[3 rows x 10 columns]

In [ ]:
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))

Accuracy r2_score 98.50646178200157
ACCURACY= 99.44885457209553
MAE= 35726.56610568274
MSE= confirmed 15    1.264520e+10
death 15        1.216583e+08
confirmed 5     1.556674e+09
death 5         1.294429e+07
dtype: float64
Final rmse value is = confirmed 15    112450.889269
death 15         11029.881083
confirmed 5      39454.711813
death 5           3597.817909
dtype: float64


In [ ]:
lr.predict([[3830010,140906]])

array([[5905644.91969191,  179077.01584222, 4428455.20207407,
         151229.72007583]])

In [ ]:
df=pd.read_csv("/content/drive/My Drive/covid data/world/world 15 and 5.csv")
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))

Accuracy r2_score 99.28690695736506
ACCURACY= 99.7270881310096
MAE= 79818.31667125065
MSE= confirmed 15    8.247906e+10
death 15        8.843040e+08
confirmed 5     9.147641e+09
death 5         9.137952e+07
dtype: float64
Final rmse value is = confirmed 15    287191.679242
death 15         29737.249910
confirmed 5      95643.301227
death 5           9559.263520
dtype: float64


In [ ]:
lr.predict([[14684741,610110]])

array([[18744939.40021707,   654440.64273313, 15897928.63988888,
          618893.1517032 ]])

In [ ]:
df=pd.read_csv("/content/drive/My Drive/covid data/UK/UK 15 and 5.csv")
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))
lr.predict([[294066,45273]])

Accuracy r2_score 96.5201267877632
ACCURACY= 97.60545466403225
MAE= 9458.523475948412
MSE= confirmed 15    1.015625e+09
death 15        2.151692e+07
confirmed 5     1.201331e+08
death 5         2.466625e+06
dtype: float64
Final rmse value is = confirmed 15    31868.877992
death 15         4638.633855
confirmed 5     10960.525965
death 5          1570.549328
dtype: float64


array([[365408.09432113,  53181.67515335, 322611.08603502,
         48867.87487883]])

In [ ]:
df=pd.read_csv('/content/drive/My Drive/covid data/Italy/Italy 5 and 15.csv')
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))
lr.predict([[244624,35058]])

Accuracy r2_score 99.54866927538711
ACCURACY= 99.12268199084791
MAE= 3022.706474920451
MSE= confirmed 15    1.204589e+08
death 15        1.190615e+06
confirmed 5     6.788745e+06
death 5         4.038589e+04
dtype: float64
Final rmse value is = confirmed 15    10975.374810
death 15         1091.153007
confirmed 5      2605.521995
death 5           200.962418
dtype: float64


array([[246179.89768425,  35611.04869114, 245815.89781541,
         35389.73570915]])

In [ ]:
df=pd.read_csv('/content/drive/My Drive/covid data/delhi/delhi confirmed and death 15 and 5.csv')
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))
lr.predict([[123747,3663]])

Accuracy r2_score 92.48472655914556
ACCURACY= 97.4474309488679
MAE= 2569.1757595741615
MSE= confirmed15    1.001041e+08
death 15       1.846737e+05
confirmed5     5.762669e+06
death 5        1.779293e+04
dtype: float64
Final rmse value is = confirmed15    10005.201782
death 15         429.736818
confirmed5      2400.556071
death 5          133.390148
dtype: float64


array([[174828.53523401,   5290.05903033, 141010.35356413,
          4225.23589936]])

In [ ]:
df=pd.read_csv('/content/drive/My Drive/covid data/gujarat/gujarat confimed and death 15 and 5.csv')
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))
lr.predict([[49353,2162]])

Accuracy r2_score 98.73899164026686
ACCURACY= 99.61438497512505
MAE= 335.0877025301883
MSE= confirmed 15    1.570510e+06
death 15        1.845491e+04
confirmed 5     1.906203e+05
death 5         1.919098e+03
dtype: float64
Final rmse value is = confirmed 15    1253.199949
death 15         135.848840
confirmed 5      436.600829
death 5           43.807513
dtype: float64


array([[72911.85661438,  2097.7674775 , 55559.28573305,  2121.70162878]])

In [ ]:
df=pd.read_csv('/content/drive/My Drive/covid data/uttarpradesh/UP  confirmed and death 15 and 5 days.csv')
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))
lr.predict([[51160,1192]])

Accuracy r2_score 99.56236929951439
ACCURACY= 99.7381592984956
MAE= 182.64632591193933
MSE= confirmed 15    407201.570361
death 15          1117.516256
confirmed 5     105368.182455
death 5            243.425385
dtype: float64
Final rmse value is = confirmed 15    638.123476
death 15         33.429272
confirmed 5     324.604656
death 5          15.602096
dtype: float64


array([[95773.435695  ,  2475.53278123, 62287.76391853,  1490.46738269]])

In [ ]:
df=pd.read_csv('/content/drive/My Drive/covid data/india/india 15 and 5 days count.csv')
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))
lr.predict([[1155191,28084]])

Accuracy r2_score 99.33406600747874
ACCURACY= 99.85801418706362
MAE= 3684.3786146569755
MSE= confirmed 15    1.685959e+08
death 15        9.390873e+05
confirmed 5     1.448221e+07
death 5         1.155320e+05
dtype: float64
Final rmse value is = confirmed 15    12984.448050
death 15          969.065171
confirmed 5      3805.549794
death 5           339.900013
dtype: float64


array([[1903457.91698151,   50048.20352158, 1359221.09383368,
          34962.48843678]])

In [ ]:
df=pd.read_csv("/content/drive/My Drive/covid data/spain/spain 15 and 5.csv")
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,[6,7,8,9]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))
lr.predict([[264836,28422]])

Accuracy r2_score 98.8912757132518
ACCURACY= 97.99636432011602
MAE= 4904.648131588289
MSE= confirmed 15    3.098951e+08
death 15        1.912989e+06
confirmed 5     2.616435e+07
death 5         2.131275e+05
dtype: float64
Final rmse value is = confirmed 15    17603.837987
death 15         1383.108533
confirmed 5      5115.110180
death 5           461.657347
dtype: float64


array([[300939.63598831,  33596.53442133, 279847.26570087,
         30411.11078386]])